name: Publish Package to npmjs
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: npx lerna bootstrap
      - run: yarn build:dev
      - run: yarn tsc
      - run: yarn build:prod
      - run: npx lerna version minor --yes
      - run: npx lerna publish from-package --yes
